[build]
  base = "v2/"
  publish = "_site"
  command = "npx tailwindcss -i ./css/index.css -o ./dist/output.css --minify && DEBUG=* eleventy"
[context.deploy-preview]
  base = "v2/"
  publish = "_site"
  command = "npx tailwindcss -i ./css/index.css -o ./dist/output.css --minify && DEBUG=* eleventy"
  