name: Trigger Netlify Build
on:
  schedule:
    - cron:  '45 5 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        env:
          NETLIFY_BUILD_HOOK_ID: ${{ secrets.NETLIFY_BUILD_HOOK_ID }}
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/$NETLIFY_BUILD_HOOK_ID"
